# -*- coding: utf-8 -*-
"""
BC Mathematics 5 - curriculum platform.

An index page lists the 19 chapters; each chapter has its own page.
Teachers sign in to write content by hand or to generate a draft with the
AI assistant. Every piece of content is tagged with its origin so a reader
can always tell curriculum text from teacher-written text from AI drafts.
"""
import os, json, sqlite3, secrets, urllib.request, urllib.error, urllib.parse, re, base64
from datetime import datetime, timezone, timedelta
from functools import wraps

from flask import (Flask, g, render_template, request, redirect, url_for,
                   session, flash, jsonify, abort, Response)
from werkzeug.security import generate_password_hash, check_password_hash
import markdown as md

BASE = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.environ.get("MATH5_DB", os.path.join(BASE, "data", "math5.sqlite3"))
SEED_PATH = os.path.join(BASE, "data", "seed.json")

# --- AI assistant configuration -------------------------------------------
API_URL = os.environ.get("ANTHROPIC_API_URL", "https://api.anthropic.com/v1/messages").strip()
API_KEY = os.environ.get("ANTHROPIC_API_KEY", "").strip()
API_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-5").strip()
API_VERSION = "2023-06-01"

SOURCES = {
    "curriculum": ("Curriculum", "Seeded from the BC learning standards"),
    "manual": ("Teacher written", "Written by hand by a teacher"),
    "ai": ("AI draft", "Generated by the AI assistant and reviewed by a teacher"),
}

# --- SMS configuration (Twilio) -------------------------------------------
# Left unset, sign-up still works: the code is written to the server log instead
# of being texted, which is enough to try the flow before paying for a provider.
SMS_SID = os.environ.get("TWILIO_ACCOUNT_SID", "").strip()
SMS_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "").strip()
SMS_FROM = os.environ.get("TWILIO_FROM_NUMBER", "").strip()
SMS_READY = bool(SMS_SID and SMS_TOKEN and SMS_FROM)

OTP_MINUTES = 10        # how long a code stays valid
OTP_MAX_ATTEMPTS = 5    # wrong guesses before the code is thrown away
OTP_MAX_SENDS = 5       # texts per sign-up attempt
OTP_RESEND_SECONDS = 60

app = Flask(__name__)
app.config["SECRET_KEY"] = os.environ.get("MATH5_SECRET_KEY") or secrets.token_hex(32)
app.config["MAX_CONTENT_LENGTH"] = 2 * 1024 * 1024


# ------------------------------------------------------------------ database
SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  pw_hash TEXT NOT NULL,
  display_name TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT 'teacher',
  created TEXT NOT NULL
);
-- the unique index on users(phone) is created after the migration below, since
-- an older database only grows that column when init_db runs
-- A sign-up is held here until its code is confirmed, so an unverified number
-- never becomes an account. The code itself is stored hashed, never in the clear.
CREATE TABLE IF NOT EXISTS signup_otp (
  phone TEXT PRIMARY KEY,
  code_hash TEXT NOT NULL,
  display_name TEXT NOT NULL,
  pw_hash TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  sends INTEGER NOT NULL DEFAULT 1,
  last_sent TEXT NOT NULL,
  expires TEXT NOT NULL,
  created TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS chapters (
  id INTEGER PRIMARY KEY,
  number INTEGER NOT NULL,
  title TEXT NOT NULL,
  strand TEXT NOT NULL DEFAULT 'Number',
  standard TEXT NOT NULL DEFAULT '',
  elaborations TEXT NOT NULL DEFAULT '[]',
  big_idea TEXT NOT NULL DEFAULT '',
  lede TEXT NOT NULL DEFAULT '',
  goals TEXT NOT NULL DEFAULT '[]',
  vocab TEXT NOT NULL DEFAULT '[]',
  body_md TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '[]',
  visual TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'manual',
  author TEXT NOT NULL DEFAULT '',
  published INTEGER NOT NULL DEFAULT 1,
  created TEXT NOT NULL,
  updated TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS questions (
  id INTEGER PRIMARY KEY,
  chapter_id INTEGER NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 1,
  type TEXT NOT NULL DEFAULT 'mcq',
  stem TEXT NOT NULL DEFAULT '',
  options TEXT NOT NULL DEFAULT '[]',
  answer TEXT NOT NULL DEFAULT '[]',
  accept TEXT NOT NULL DEFAULT '[]',
  display_answer TEXT NOT NULL DEFAULT '',
  unit TEXT NOT NULL DEFAULT '',
  visual TEXT NOT NULL DEFAULT '',
  explanation TEXT NOT NULL DEFAULT '',
  skill_tag TEXT NOT NULL DEFAULT '',
  difficulty TEXT NOT NULL DEFAULT 'medium',
  source TEXT NOT NULL DEFAULT 'manual',
  author TEXT NOT NULL DEFAULT '',
  created TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS ai_log (
  id INTEGER PRIMARY KEY,
  username TEXT NOT NULL,
  kind TEXT NOT NULL,
  brief TEXT NOT NULL,
  ok INTEGER NOT NULL,
  detail TEXT NOT NULL DEFAULT '',
  created TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_q_chapter ON questions(chapter_id, position);
CREATE INDEX IF NOT EXISTS idx_ch_number ON chapters(number);
"""


def now():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")


def db():
    if "db" not in g:
        os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
        g.db = sqlite3.connect(DB_PATH, timeout=30)
        g.db.row_factory = sqlite3.Row
        g.db.execute("PRAGMA foreign_keys = ON")
        g.db.execute("PRAGMA busy_timeout = 30000")
    return g.db


@app.teardown_appcontext
def close_db(exc):
    d = g.pop("db", None)
    if d is not None:
        d.close()


def init_db():
    """Create the schema, seed the curriculum chapters, add the first teacher.

    A WSGI server such as gunicorn imports this module once per worker, so
    several processes may call this at the same moment on a cold start. The
    seeding runs inside BEGIN IMMEDIATE, which takes the write lock before the
    row count is read: the first worker seeds, and every other worker waits,
    then sees a non-empty table and does nothing. A unique index on the chapter
    number is the backstop if that ever fails.
    """
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    con = sqlite3.connect(DB_PATH, timeout=30, isolation_level=None)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA busy_timeout = 30000")
    con.executescript(SCHEMA)
    try:
        con.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_ch_number_uniq"
                    " ON chapters(number)")
    except sqlite3.IntegrityError:
        pass  # an existing database already holds duplicate numbers; leave it alone

    # a database created before the 'visual' column existed needs it added by hand
    for tbl in ("chapters", "questions"):
        try:
            con.execute("ALTER TABLE %s ADD COLUMN visual TEXT NOT NULL DEFAULT ''" % tbl)
        except sqlite3.OperationalError:
            pass  # column already present
    # likewise for the phone column added with mobile sign-up
    try:
        con.execute("ALTER TABLE users ADD COLUMN phone TEXT NOT NULL DEFAULT ''")
    except sqlite3.OperationalError:
        pass
    con.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phone"
                " ON users(phone) WHERE phone <> ''")

    con.execute("BEGIN IMMEDIATE")
    have = con.execute("SELECT COUNT(*) c FROM chapters").fetchone()["c"]
    if have == 0 and os.path.exists(SEED_PATH):
        with open(SEED_PATH, encoding="utf-8") as fh:
            seed = json.load(fh)   # explicit: Windows would otherwise decode it as cp1252
        for c in seed["chapters"]:
            cur = con.execute(
                "INSERT INTO chapters (number,title,strand,standard,elaborations,"
                "big_idea,lede,goals,vocab,body_md,summary,visual,source,author,published,"
                "created,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,'curriculum','BC Curriculum',1,?,?)",
                (c["number"], c["title"], c["strand"], c["standard"],
                 json.dumps(c["elaborations"]), c["big_idea"], c["lede"],
                 json.dumps(c["goals"]), json.dumps(c["vocab"]), c["body_md"],
                 json.dumps(c["summary"]), c.get("visual", ""), now(), now()))
            cid = cur.lastrowid
            for q in c["questions"]:
                con.execute(
                    "INSERT INTO questions (chapter_id,position,type,stem,options,answer,"
                    "accept,display_answer,unit,visual,explanation,skill_tag,difficulty,source,"
                    "author,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,'curriculum','BC Curriculum',?)",
                    (cid, q["position"], q["type"], q["stem"], json.dumps(q["options"]),
                     json.dumps(q["answer"]), json.dumps(q["accept"]),
                     q["display_answer"], q["unit"], q.get("visual", ""), q["explanation"],
                     q["skill_tag"], q["difficulty"], now()))
        print("seeded %d chapters" % len(seed["chapters"]))

    users = con.execute("SELECT COUNT(*) c FROM users").fetchone()["c"]
    created_pw = None
    if users == 0:
        pw = os.environ.get("MATH5_ADMIN_PASSWORD")
        if not pw:
            pw = secrets.token_urlsafe(9)
            created_pw = pw
        con.execute("INSERT INTO users (username,pw_hash,display_name,role,created)"
                    " VALUES (?,?,?,?,?)",
                    ("teacher", generate_password_hash(pw), "Lead Teacher", "admin", now()))
    con.commit()
    con.close()
    if created_pw:
        print("\n" + "=" * 58)
        print("  First-run teacher account created")
        print("  username: teacher")
        print("  password: %s" % created_pw)
        print("  Change it from the teacher dashboard after signing in.")
        print("=" * 58 + "\n")


# ------------------------------------------------------------------- helpers
def jl(s, default=None):
    try:
        v = json.loads(s)
        return v if v is not None else (default if default is not None else [])
    except Exception:
        return default if default is not None else []


MD = md.Markdown(extensions=["tables", "fenced_code"])


def render_md(text):
    MD.reset()
    return MD.convert(text or "")


def current_user():
    if "uid" not in session:
        return None
    if "_u" not in g:
        g._u = db().execute("SELECT * FROM users WHERE id=?", (session["uid"],)).fetchone()
    return g._u


def login_required(fn):
    @wraps(fn)
    def inner(*a, **kw):
        if not current_user():
            flash("Please sign in to reach the teacher area.", "warn")
            return redirect(url_for("login", next=request.path))
        return fn(*a, **kw)
    return inner


# ------------------------------------------------------- mobile sign-up
PHONE_DIGITS = re.compile(r"[^0-9+]")


def normalize_phone(raw):
    """Reduce what someone typed to a comparable form: digits with an optional
    leading +. Spaces, dashes and brackets are all dropped, so '+1 (604) 555-0132'
    and '+16045550132' are the same number. Returns '' if it cannot be one."""
    s = PHONE_DIGITS.sub("", (raw or "").strip())
    if s.startswith("+"):
        s = "+" + s[1:].replace("+", "")
    else:
        s = s.replace("+", "")
    digits = s.lstrip("+")
    if not digits.isdigit() or not (7 <= len(digits) <= 15):
        return ""
    return s


def send_sms(to, body):
    """Text `body` to `to`. Returns (sent, error). With no provider configured
    the code goes to the server log instead, and sent is False with no error."""
    if not SMS_READY:
        print("\n[sign-up] SMS is not configured. Code for %s: %s\n" % (to, body))
        return False, None
    url = "https://api.twilio.com/2010-04-01/Accounts/%s/Messages.json" % SMS_SID
    data = urllib.parse.urlencode({"From": SMS_FROM, "To": to, "Body": body}).encode()
    auth = base64.b64encode(("%s:%s" % (SMS_SID, SMS_TOKEN)).encode()).decode()
    req = urllib.request.Request(url, data=data, method="POST", headers={
        "Authorization": "Basic %s" % auth,
        "Content-Type": "application/x-www-form-urlencoded",
    })
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            r.read()
        return True, None
    except urllib.error.HTTPError as e:
        try:
            msg = json.loads(e.read().decode()).get("message", "HTTP %s" % e.code)
        except Exception:
            msg = "HTTP %s from the SMS provider." % e.code
        return False, msg
    except Exception as e:
        return False, "Could not reach the SMS provider: %s" % e


def start_otp(phone, display_name, pw_hash):
    """Create or replace the pending sign-up for this number and text a code."""
    code = "%06d" % secrets.randbelow(1000000)
    expires = (datetime.now(timezone.utc) + timedelta(minutes=OTP_MINUTES)
               ).strftime("%Y-%m-%d %H:%M:%S")
    db().execute(
        "INSERT INTO signup_otp (phone,code_hash,display_name,pw_hash,attempts,sends,"
        "last_sent,expires,created) VALUES (?,?,?,?,0,1,?,?,?) "
        "ON CONFLICT(phone) DO UPDATE SET code_hash=excluded.code_hash,"
        "display_name=excluded.display_name, pw_hash=excluded.pw_hash, attempts=0,"
        "sends=signup_otp.sends+1, last_sent=excluded.last_sent, expires=excluded.expires",
        (phone, generate_password_hash(code), display_name, pw_hash, now(), expires, now()))
    db().commit()
    return send_sms(phone, "Your Mathematics 5 verification code is %s. "
                           "It expires in %d minutes." % (code, OTP_MINUTES))


def admin_required(fn):
    """Managing accounts is the one thing a plain teacher cannot do: every
    signed-in teacher may write content, but only an admin lets someone new in."""
    @wraps(fn)
    def inner(*a, **kw):
        u = current_user()
        if not u:
            flash("Please sign in to reach the teacher area.", "warn")
            return redirect(url_for("login", next=request.path))
        if u["role"] != "admin":
            flash("Only an admin can manage teacher accounts.", "error")
            return redirect(url_for("dashboard"))
        return fn(*a, **kw)
    return inner


@app.context_processor
def inject():
    return dict(user=current_user(), SOURCES=SOURCES,
                ai_ready=bool(API_KEY), course="Mathematics 5", grade=5)


def chapter_row(number):
    r = db().execute("SELECT * FROM chapters WHERE number=?", (number,)).fetchone()
    if not r:
        abort(404)
    return r


def questions_for(cid):
    rows = db().execute(
        "SELECT * FROM questions WHERE chapter_id=? ORDER BY position, id", (cid,)).fetchall()
    out = []
    for r in rows:
        d = dict(r)
        d["options"] = jl(r["options"])
        d["answer"] = jl(r["answer"])
        d["accept"] = jl(r["accept"])
        out.append(d)
    return out


def chapter_dict(r):
    d = dict(r)
    d["elaborations"] = jl(r["elaborations"])
    d["goals"] = jl(r["goals"])
    d["vocab"] = jl(r["vocab"])
    d["summary"] = jl(r["summary"])
    d["body_html"] = render_md(r["body_md"])
    d["lesson_count"] = r["body_md"].count("### Lesson")
    return d


def split_lines(text):
    return [x.strip() for x in (text or "").splitlines() if x.strip()]


STRANDS = ["Number", "Computational Fluency", "Patterning",
           "Geometry and Measurement", "Data and Probability"]

# --------------------------------------------------------- chart colour map
# A 5-hue categorical set validated with the dataviz palette checker
# (chroma floor, CVD deuteranopia/protanopia/tritanopia separation, contrast)
# for both this app's light paper surface and its dark ink surface.
CHART_BLUE, CHART_AMBER, CHART_GREEN, CHART_RED, CHART_PURPLE = (
    "#1b6fd4", "#c9750d", "#1f9d6c", "#b4302b", "#7a4fc9")
TYPE_LABELS = {"mcq": "Multiple choice", "multi": "Multi-select", "fill": "Fill in the blank"}
TYPE_COLORS = {"mcq": CHART_BLUE, "multi": CHART_GREEN, "fill": CHART_AMBER}
SOURCE_COLORS = {"curriculum": CHART_BLUE, "manual": CHART_GREEN, "ai": CHART_AMBER}
STRAND_COLORS = dict(zip(STRANDS, [CHART_BLUE, CHART_AMBER, CHART_GREEN, CHART_RED, CHART_PURPLE]))


def bar_segments(pairs, width=200, gap=2):
    """Turn [(label,color,count), ...] into rounded-rect segments for an
    inline SVG stacked bar: a thin horizontal chart with a 2px gap between
    fills, sized for a `width`-unit viewBox. Zero-count entries are dropped
    so the legend only lists what is actually present."""
    items = [(l, c, n) for l, c, n in pairs if n]
    total = sum(n for _, _, n in items)
    segments = []
    if not total:
        return segments, 0
    avail = width - gap * (len(items) - 1) if len(items) > 1 else width
    x = 0.0
    for label, color, count in items:
        w = count / total * avail
        segments.append(dict(label=label, color=color, count=count,
                             pct=round(count / total * 100), x=round(x, 2), width=round(w, 2)))
        x += w + gap
    return segments, total


# -------------------------------------------------------------- public pages
@app.route("/")
def index():
    rows = db().execute(
        "SELECT c.*, (SELECT COUNT(*) FROM questions q WHERE q.chapter_id=c.id) nq "
        "FROM chapters c WHERE c.published=1 ORDER BY c.number").fetchall()
    chapters = []
    for r in rows:
        chapters.append(dict(number=r["number"], title=r["title"], strand=r["strand"],
                             standard=r["standard"], lede=r["lede"], source=r["source"],
                             nq=r["nq"], lessons=r["body_md"].count("### Lesson")))
    stats = dict(
        chapters=len(chapters),
        lessons=sum(c["lessons"] for c in chapters),
        questions=sum(c["nq"] for c in chapters),
        standards=len({c["standard"] for c in chapters if c["standard"]}),
    )
    by_strand = [(s, [c for c in chapters if c["strand"] == s]) for s in STRANDS]
    by_strand = [(s, cs) for s, cs in by_strand if cs]
    strand_chart, _ = bar_segments([(s, STRAND_COLORS[s], len(cs)) for s, cs in by_strand])
    qtypes = dict(db().execute(
        "SELECT q.type, COUNT(*) FROM questions q JOIN chapters c ON c.id=q.chapter_id"
        " WHERE c.published=1 GROUP BY q.type").fetchall())
    type_chart, _ = bar_segments([(TYPE_LABELS[t], TYPE_COLORS[t], qtypes.get(t, 0))
                                  for t in ("fill", "mcq", "multi")])
    return render_template("index.html", chapters=chapters, stats=stats,
                           by_strand=by_strand, strand_chart=strand_chart,
                           type_chart=type_chart)


@app.route("/chapter/<int:number>")
def chapter(number):
    r = chapter_row(number)
    if not r["published"] and not current_user():
        abort(404)
    c = chapter_dict(r)
    qs = questions_for(r["id"])
    nums = [x["number"] for x in db().execute(
        "SELECT number FROM chapters WHERE published=1 ORDER BY number").fetchall()]
    i = nums.index(number) if number in nums else -1
    prev_n = nums[i - 1] if i > 0 else None
    next_n = nums[i + 1] if 0 <= i < len(nums) - 1 else None
    quiz = {}
    for q in qs:
        quiz["q%d" % q["id"]] = dict(t=q["type"], why=q["explanation"],
                                     ans=q["answer"], accept=q["accept"],
                                     show=q["display_answer"])
    tally = {}
    for q in qs:
        tally[q["type"]] = tally.get(q["type"], 0) + 1
    comp_chart, _ = bar_segments([(TYPE_LABELS[t], TYPE_COLORS[t], tally.get(t, 0))
                                  for t in ("fill", "mcq", "multi")])
    return render_template("chapter.html", c=c, questions=qs, quiz_json=json.dumps(quiz),
                           prev_n=prev_n, next_n=next_n, tally=tally, comp_chart=comp_chart,
                           all_numbers=nums)


@app.route("/api/course.json")
def course_json():
    rows = db().execute("SELECT * FROM chapters ORDER BY number").fetchall()
    out = []
    for r in rows:
        c = dict(chapter_id="G5-MATH-CH%02d" % r["number"], number=r["number"],
                 title=r["title"], strand=r["strand"], content_standard=r["standard"],
                 elaborations=jl(r["elaborations"]), big_idea=r["big_idea"],
                 learning_goals=jl(r["goals"]), vocabulary=jl(r["vocab"]),
                 summary=jl(r["summary"]), source=r["source"], author=r["author"],
                 published=bool(r["published"]), questions=[])
        for q in questions_for(r["id"]):
            c["questions"].append({k: q[k] for k in
                ("position", "type", "stem", "options", "answer", "accept",
                 "display_answer", "unit", "visual", "explanation", "skill_tag",
                 "difficulty", "source")})
        out.append(c)
    return Response(json.dumps(dict(course="Mathematics 5", grade=5,
                    curriculum="British Columbia", chapter_count=len(out),
                    question_count=sum(len(c["questions"]) for c in out),
                    chapters=out), indent=1, ensure_ascii=False),
                    mimetype="application/json")


@app.route("/healthz")
def healthz():
    n = db().execute("SELECT COUNT(*) c FROM chapters").fetchone()["c"]
    return jsonify(status="ok", chapters=n, ai_configured=bool(API_KEY))


# -------------------------------------------------------------------- auth
@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        # Someone who signed up by mobile knows their number, not the username
        # that was generated for them, so either one is accepted here.
        ident = request.form.get("username", "").strip().lower()
        phone = normalize_phone(ident)
        u = db().execute(
            "SELECT * FROM users WHERE username=? OR (phone <> '' AND phone=?)",
            (ident, phone or "\x00")).fetchone()
        if u and check_password_hash(u["pw_hash"], request.form.get("password", "")):
            session.clear()
            session["uid"] = u["id"]
            nxt = request.form.get("next") or url_for("dashboard")
            if not nxt.startswith("/"):
                nxt = url_for("dashboard")
            return redirect(nxt)
        flash("Those details did not match an account.", "error")
    return render_template("login.html", next=request.args.get("next", ""))


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("index"))


@app.route("/signup", methods=["GET", "POST"])
def signup():
    """Step one: take the details, hold them aside, and text a code to the number.
    Nothing is written to `users` until the code comes back verified."""
    if current_user():
        return redirect(url_for("dashboard"))
    if request.method == "POST":
        f = request.form
        display = f.get("display_name", "").strip()
        phone = normalize_phone(f.get("phone"))
        pw = f.get("password", "")
        if not display:
            flash("Give your name, so your colleagues know who wrote what.", "error")
        elif not phone:
            flash("Enter a mobile number, including the country code, e.g. +16045550132.",
                  "error")
        elif len(pw) < 8:
            flash("Choose a password of at least 8 characters.", "error")
        elif db().execute("SELECT 1 FROM users WHERE phone=?", (phone,)).fetchone():
            flash("There is already an account for that mobile number. Sign in instead.",
                  "warn")
            return redirect(url_for("login"))
        else:
            row = db().execute("SELECT sends, last_sent FROM signup_otp WHERE phone=?",
                               (phone,)).fetchone()
            if row and row["sends"] >= OTP_MAX_SENDS:
                flash("That number has been sent too many codes. Try again later.", "error")
                return redirect(url_for("signup"))
            sent, err = start_otp(phone, display, generate_password_hash(pw))
            if err:
                flash("The code could not be sent: %s" % err, "error")
                return redirect(url_for("signup"))
            session["signup_phone"] = phone
            # when SMS is off the verify page already explains where the code went
            return redirect(url_for("signup_verify"))
        return redirect(url_for("signup"))
    return render_template("signup.html")


@app.route("/signup/verify", methods=["GET", "POST"])
def signup_verify():
    """Step two: check the code, then create the account and sign them in."""
    phone = session.get("signup_phone")
    if not phone:
        return redirect(url_for("signup"))
    row = db().execute("SELECT * FROM signup_otp WHERE phone=?", (phone,)).fetchone()
    if not row:
        flash("That code has expired. Please sign up again.", "warn")
        session.pop("signup_phone", None)
        return redirect(url_for("signup"))

    if request.method == "POST":
        if request.form.get("resend"):
            if row["sends"] >= OTP_MAX_SENDS:
                flash("That number has been sent too many codes. Try again later.", "error")
            elif row["last_sent"] >= (datetime.now(timezone.utc) -
                                      timedelta(seconds=OTP_RESEND_SECONDS)
                                      ).strftime("%Y-%m-%d %H:%M:%S"):
                flash("A code was just sent. Wait a minute before asking for another.", "warn")
            else:
                sent, err = start_otp(phone, row["display_name"], row["pw_hash"])
                flash(("The code could not be sent: %s" % err) if err else
                      ("A new code is on its way." if sent else
                       "A new code was written to the server log."),
                      "error" if err else "ok")
            return redirect(url_for("signup_verify"))

        if row["expires"] < now():
            db().execute("DELETE FROM signup_otp WHERE phone=?", (phone,))
            db().commit()
            flash("That code has expired. Please sign up again.", "warn")
            session.pop("signup_phone", None)
            return redirect(url_for("signup"))
        code = re.sub(r"\D", "", request.form.get("code", ""))
        if not check_password_hash(row["code_hash"], code):
            attempts = row["attempts"] + 1
            if attempts >= OTP_MAX_ATTEMPTS:
                # spent: throw the code away on this request rather than the next
                db().execute("DELETE FROM signup_otp WHERE phone=?", (phone,))
                db().commit()
                session.pop("signup_phone", None)
                flash("Too many wrong codes. Please sign up again.", "error")
                return redirect(url_for("signup"))
            db().execute("UPDATE signup_otp SET attempts=? WHERE phone=?", (attempts, phone))
            db().commit()
            left = OTP_MAX_ATTEMPTS - attempts
            flash("That code did not match. %d %s left."
                  % (left, "try" if left == 1 else "tries"), "error")
            return redirect(url_for("signup_verify"))

        # Verified. Build a username from the number, since it is already unique.
        username = "t" + phone.lstrip("+")[-10:]
        n = 0
        while db().execute("SELECT 1 FROM users WHERE username=?", (username,)).fetchone():
            n += 1
            username = "t%s-%d" % (phone.lstrip("+")[-10:], n)
        cur = db().execute(
            "INSERT INTO users (username,pw_hash,display_name,phone,role,created)"
            " VALUES (?,?,?,?,'teacher',?)",
            (username, row["pw_hash"], row["display_name"], phone, now()))
        db().execute("DELETE FROM signup_otp WHERE phone=?", (phone,))
        db().commit()
        session.clear()
        session["uid"] = cur.lastrowid
        flash("Welcome, %s. Your mobile number is verified and you are signed in."
              % row["display_name"], "ok")
        return redirect(url_for("dashboard"))

    return render_template("signup_verify.html", phone=phone, sms_ready=SMS_READY)


@app.route("/teacher/password", methods=["POST"])
@login_required
def change_password():
    u = current_user()
    old = request.form.get("old", "")
    new = request.form.get("new", "")
    if not check_password_hash(u["pw_hash"], old):
        flash("Your current password was not correct.", "error")
    elif len(new) < 8:
        flash("Choose a password of at least 8 characters.", "error")
    else:
        db().execute("UPDATE users SET pw_hash=? WHERE id=?",
                     (generate_password_hash(new), u["id"]))
        db().commit()
        flash("Password changed.", "ok")
    return redirect(url_for("dashboard"))


# ------------------------------------------------------------ teacher accounts
# There is no public sign-up: a teacher gets in only when an admin creates the
# account here, so a site on a public URL cannot be joined by a stranger.
USERNAME_OK = re.compile(r"^[a-z0-9._-]{3,32}$")


@app.route("/teacher/users/new", methods=["POST"])
@admin_required
def add_user():
    f = request.form
    username = f.get("username", "").strip().lower()
    display = f.get("display_name", "").strip()
    pw = f.get("password", "")
    role = "admin" if f.get("role") == "admin" else "teacher"

    if not USERNAME_OK.match(username):
        flash("A username needs 3 to 32 characters: letters, digits, dot, dash "
              "or underscore.", "error")
    elif not display:
        flash("Give the teacher a display name.", "error")
    elif len(pw) < 8:
        flash("Set a first password of at least 8 characters.", "error")
    else:
        try:
            db().execute("INSERT INTO users (username,pw_hash,display_name,role,created)"
                         " VALUES (?,?,?,?,?)",
                         (username, generate_password_hash(pw), display, role, now()))
            db().commit()
            flash("Account created for %s. Ask them to sign in and change the "
                  "password from this page." % display, "ok")
        except sqlite3.IntegrityError:
            flash("The username '%s' is already taken." % username, "error")
    return redirect(url_for("dashboard"))


@app.route("/teacher/users/<int:uid>/delete", methods=["POST"])
@admin_required
def delete_user(uid):
    me = current_user()
    target = db().execute("SELECT * FROM users WHERE id=?", (uid,)).fetchone()
    if not target:
        abort(404)
    # Only an admin reaches this, and an admin cannot remove themselves, so the
    # site can never be left without one.
    if target["id"] == me["id"]:
        flash("You cannot remove your own account.", "error")
    else:
        db().execute("DELETE FROM users WHERE id=?", (uid,))
        db().commit()
        flash("Removed the account for %s. Their chapters and questions stay, "
              "still credited to them." % target["display_name"], "ok")
    return redirect(url_for("dashboard"))


# --------------------------------------------------------------- teacher UI
@app.route("/teacher")
@login_required
def dashboard():
    rows = db().execute(
        "SELECT c.*, (SELECT COUNT(*) FROM questions q WHERE q.chapter_id=c.id) nq "
        "FROM chapters c ORDER BY c.number").fetchall()
    chapters = [dict(number=r["number"], title=r["title"], strand=r["strand"],
                     source=r["source"], author=r["author"], nq=r["nq"],
                     published=r["published"], updated=r["updated"],
                     lessons=r["body_md"].count("### Lesson")) for r in rows]
    counts = {}
    for r in rows:
        counts[r["source"]] = counts.get(r["source"], 0) + 1
    qsrc = dict(db().execute(
        "SELECT source, COUNT(*) FROM questions GROUP BY source").fetchall())
    src_order = [("curriculum", "Curriculum"), ("manual", "Teacher written"), ("ai", "AI draft")]
    ch_chart, _ = bar_segments([(lbl, SOURCE_COLORS[k], counts.get(k, 0)) for k, lbl in src_order])
    q_chart, _ = bar_segments([(lbl, SOURCE_COLORS[k], qsrc.get(k, 0)) for k, lbl in src_order])
    logs = db().execute("SELECT * FROM ai_log ORDER BY id DESC LIMIT 8").fetchall()
    teachers = db().execute("SELECT id, username, display_name, phone, role, created"
                            " FROM users ORDER BY role, username").fetchall()
    return render_template("dashboard.html", chapters=chapters, counts=counts,
                           qsrc=qsrc, logs=logs, ch_chart=ch_chart, q_chart=q_chart,
                           teachers=teachers)


@app.route("/teacher/chapter/new", methods=["GET", "POST"])
@app.route("/teacher/chapter/<int:number>/edit", methods=["GET", "POST"])
@login_required
def edit_chapter(number=None):
    row = chapter_row(number) if number else None
    if request.method == "POST":
        f = request.form
        try:
            num = int(f.get("number") or 0)
        except ValueError:
            num = 0
        if num < 1:
            flash("Give the chapter a number of 1 or more.", "error")
            return redirect(request.path)
        title = f.get("title", "").strip()
        if not title:
            flash("A chapter needs a title.", "error")
            return redirect(request.path)
        vocab = []
        for line in split_lines(f.get("vocab")):
            term, _, meaning = line.partition("|")
            vocab.append(dict(term=term.strip(), meaning=meaning.strip()))
        vals = (num, title, f.get("strand", "Number"), f.get("standard", "").strip(),
                json.dumps(split_lines(f.get("elaborations"))),
                f.get("big_idea", "").strip(), f.get("lede", "").strip(),
                json.dumps(split_lines(f.get("goals"))), json.dumps(vocab),
                f.get("body_md", ""), json.dumps(split_lines(f.get("summary"))),
                f.get("visual", "").strip(),
                1 if f.get("published") else 0)
        clash = db().execute("SELECT id FROM chapters WHERE number=? AND id IS NOT ?",
                             (num, row["id"] if row else None)).fetchone()
        if clash:
            flash("Chapter %d already exists. Pick another number." % num, "error")
            return redirect(request.path)
        if row:
            src = row["source"]
            if src == "curriculum":
                src = "manual"      # a curriculum chapter edited by hand is now teacher-written
            db().execute(
                "UPDATE chapters SET number=?,title=?,strand=?,standard=?,elaborations=?,"
                "big_idea=?,lede=?,goals=?,vocab=?,body_md=?,summary=?,visual=?,published=?,"
                "source=?,author=?,updated=? WHERE id=?",
                vals + (src, current_user()["display_name"], now(), row["id"]))
            db().commit()
            flash("Chapter %d saved." % num, "ok")
            return redirect(url_for("chapter", number=num))
        cur = db().execute(
            "INSERT INTO chapters (number,title,strand,standard,elaborations,big_idea,"
            "lede,goals,vocab,body_md,summary,visual,published,source,author,created,updated)"
            " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            vals + (f.get("source") or "manual", current_user()["display_name"], now(), now()))
        db().commit()
        flash("Chapter %d created." % num, "ok")
        return redirect(url_for("chapter", number=num))

    c = chapter_dict(row) if row else None
    if c:
        c["vocab_text"] = "\n".join("%s | %s" % (v.get("term", ""), v.get("meaning", ""))
                                    for v in c["vocab"])
    nxt = db().execute("SELECT COALESCE(MAX(number),0)+1 n FROM chapters").fetchone()["n"]
    return render_template("chapter_edit.html", c=c, strands=STRANDS, next_number=nxt,
                           prefill=session.pop("prefill_chapter", None))


@app.route("/teacher/chapter/<int:number>/delete", methods=["POST"])
@login_required
def delete_chapter(number):
    row = chapter_row(number)
    db().execute("DELETE FROM chapters WHERE id=?", (row["id"],))
    db().commit()
    flash("Chapter %d deleted." % number, "ok")
    return redirect(url_for("dashboard"))


@app.route("/teacher/chapter/<int:number>/publish", methods=["POST"])
@login_required
def toggle_publish(number):
    row = chapter_row(number)
    db().execute("UPDATE chapters SET published=?, updated=? WHERE id=?",
                 (0 if row["published"] else 1, now(), row["id"]))
    db().commit()
    return redirect(url_for("dashboard"))


# --------------------------------------------------------------- questions
def read_question_form(f):
    qtype = f.get("type", "mcq")
    opts = split_lines(f.get("options"))
    if qtype == "fill":
        accept = split_lines(f.get("accept"))
        return dict(type=qtype, stem=f.get("stem", "").strip(), options=[],
                    answer=[], accept=accept,
                    display_answer=(f.get("display_answer") or (accept[0] if accept else "")),
                    unit=f.get("unit", "").strip(),
                    visual=f.get("visual", "").strip(),
                    explanation=f.get("explanation", "").strip(),
                    skill_tag=f.get("skill_tag", "").strip(),
                    difficulty=f.get("difficulty", "medium")), None
    picked = [int(x) for x in f.getlist("correct") if x.isdigit()]
    picked = sorted({i for i in picked if 0 <= i < len(opts)})
    if len(opts) < 2:
        return None, "Give at least two options."
    if not picked:
        return None, "Mark at least one option as correct."
    if qtype == "mcq" and len(picked) > 1:
        return None, "A multiple-choice question needs exactly one correct option. Use multi-select for more."
    keys = ["A", "B", "C", "D", "E", "F"]
    return dict(type=qtype, stem=f.get("stem", "").strip(), options=opts,
                answer=picked, accept=[],
                display_answer=" and ".join(keys[i] for i in picked),
                unit="", visual=f.get("visual", "").strip(),
                explanation=f.get("explanation", "").strip(),
                skill_tag=f.get("skill_tag", "").strip(),
                difficulty=f.get("difficulty", "medium")), None


@app.route("/teacher/chapter/<int:number>/question/new", methods=["GET", "POST"])
@app.route("/teacher/chapter/<int:number>/question/<int:qid>", methods=["GET", "POST"])
@login_required
def edit_question(number, qid=None):
    ch = chapter_row(number)
    q = None
    if qid:
        q = db().execute("SELECT * FROM questions WHERE id=? AND chapter_id=?",
                         (qid, ch["id"])).fetchone()
        if not q:
            abort(404)
    if request.method == "POST":
        data, err = read_question_form(request.form)
        if err:
            flash(err, "error")
            return redirect(request.path)
        if not data["stem"]:
            flash("A question needs a stem.", "error")
            return redirect(request.path)
        if q:
            src = q["source"]
            if src == "curriculum":
                src = "manual"
            db().execute(
                "UPDATE questions SET type=?,stem=?,options=?,answer=?,accept=?,"
                "display_answer=?,unit=?,visual=?,explanation=?,skill_tag=?,difficulty=?,"
                "source=?,author=? WHERE id=?",
                (data["type"], data["stem"], json.dumps(data["options"]),
                 json.dumps(data["answer"]), json.dumps(data["accept"]),
                 data["display_answer"], data["unit"], data["visual"], data["explanation"],
                 data["skill_tag"], data["difficulty"], src,
                 current_user()["display_name"], q["id"]))
            flash("Question saved.", "ok")
        else:
            pos = db().execute("SELECT COALESCE(MAX(position),0)+1 p FROM questions"
                               " WHERE chapter_id=?", (ch["id"],)).fetchone()["p"]
            db().execute(
                "INSERT INTO questions (chapter_id,position,type,stem,options,answer,"
                "accept,display_answer,unit,visual,explanation,skill_tag,difficulty,source,"
                "author,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (ch["id"], pos, data["type"], data["stem"], json.dumps(data["options"]),
                 json.dumps(data["answer"]), json.dumps(data["accept"]),
                 data["display_answer"], data["unit"], data["visual"], data["explanation"],
                 data["skill_tag"], data["difficulty"],
                 request.form.get("source") or "manual",
                 current_user()["display_name"], now()))
            flash("Question added.", "ok")
        db().commit()
        return redirect(url_for("questions_list", number=number))

    qd = None
    if q:
        qd = dict(q)
        qd["options"] = jl(q["options"])
        qd["answer"] = jl(q["answer"])
        qd["accept"] = jl(q["accept"])
    return render_template("question_edit.html", ch=ch, q=qd,
                           prefill=session.pop("prefill_question", None))


@app.route("/teacher/chapter/<int:number>/questions")
@login_required
def questions_list(number):
    ch = chapter_row(number)
    return render_template("questions.html", ch=ch, questions=questions_for(ch["id"]))


@app.route("/teacher/question/<int:qid>/delete", methods=["POST"])
@login_required
def delete_question(qid):
    q = db().execute("SELECT q.*, c.number FROM questions q JOIN chapters c"
                     " ON c.id=q.chapter_id WHERE q.id=?", (qid,)).fetchone()
    if not q:
        abort(404)
    db().execute("DELETE FROM questions WHERE id=?", (qid,))
    db().commit()
    flash("Question deleted.", "ok")
    return redirect(url_for("questions_list", number=q["number"]))


# ------------------------------------------------------------- AI assistant
PROMPTS = {
 "lesson": """Write one lesson for a Grade 5 mathematics chapter in British Columbia.

Return Markdown only, in exactly this shape:

### Lesson <number> - <short title>

<one or two sentences stating the concept plainly>

<a fenced code block showing a worked example, laid out step by step>

<a short paragraph or a small Markdown table if it helps>

> **Watch out.** <the single most common student error, and how to avoid it>

Rules: British Columbia Grade 5 level. Plain language a 10-year-old reads comfortably.
Use ASCII only inside code blocks, no unicode box characters. Do not use the
multiplication sign; write x. Separate thousands with a space, as in 1 250 000.
No preamble, no closing remarks, no headings other than the one shown.""",

 "questions": """Write assessment questions for a Grade 5 mathematics chapter in British Columbia.

Return a JSON array only. No prose, no markdown fences. Each element:

{"type":"mcq","stem":"...","options":["...","...","...","..."],"answer":[2],
 "explanation":"why the correct option is correct","skill_tag":"short-kebab-tag",
 "difficulty":"easy|medium|hard"}

{"type":"multi","stem":"... Select every ...","options":["..","..","..","..",".."],
 "answer":[0,2,4],"explanation":"...","skill_tag":"...","difficulty":"..."}

{"type":"fill","stem":"...","accept":["42","42.0"],"display_answer":"42",
 "unit":"","explanation":"...","skill_tag":"...","difficulty":"..."}

Rules: "answer" holds zero-based indexes into "options". mcq has exactly one
index; multi has two or more. For fill, "accept" lists every spelling a
student might reasonably type, including forms with and without spaces in
numbers. Every arithmetic answer must be correct: check it before writing it.
Grade 5 level, plain language. Write x for multiplication, not the times sign.""",

 "explain": """Explain this Grade 5 mathematics idea for a teacher to read aloud to the class.
Return plain Markdown: two or three short paragraphs, then a worked example in a
fenced code block, then one line beginning "Watch out." naming the usual student error.
No preamble. Plain language. Write x for multiplication.""",

 "rewrite": """Rewrite the text below so a Grade 5 student who finds reading difficult can
follow it. Keep every mathematical fact exactly as it is. Use shorter sentences
and commoner words. Keep any code blocks and tables. Return Markdown only, no
preamble and no commentary on what you changed.""",

 "vocab": """List the key vocabulary for this Grade 5 mathematics topic.
Return one term per line in the form:

Term | A plain-language meaning in one sentence

Six to eight terms. No preamble, no numbering, no markdown formatting.""",
}


def call_claude(system, user, max_tokens=2000):
    """POST to the Claude Messages API. Returns (text, error)."""
    if not API_KEY:
        return None, ("The AI assistant is switched off because no API key is set. "
                      "Set ANTHROPIC_API_KEY in the environment and restart the server.")
    payload = json.dumps({
        "model": API_MODEL,
        "max_tokens": max_tokens,
        "system": system,
        "messages": [{"role": "user", "content": user}],
    }).encode()
    req = urllib.request.Request(API_URL, data=payload, method="POST", headers={
        "content-type": "application/json",
        "x-api-key": API_KEY,
        "anthropic-version": API_VERSION,
    })
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            body = json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        try:
            msg = json.loads(e.read().decode())["error"]["message"]
        except Exception:
            msg = "HTTP %s from the API." % e.code
        return None, msg
    except urllib.error.URLError as e:
        return None, "Could not reach the API: %s" % e.reason
    except Exception as e:
        return None, "Unexpected error: %s" % e
    text = "".join(b.get("text", "") for b in body.get("content", [])
                   if b.get("type") == "text").strip()
    if not text:
        return None, "The API returned no text."
    return text, None


def log_ai(kind, brief, ok, detail=""):
    db().execute("INSERT INTO ai_log (username,kind,brief,ok,detail,created)"
                 " VALUES (?,?,?,?,?,?)",
                 (current_user()["username"], kind, brief[:180], 1 if ok else 0,
                  detail[:300], now()))
    db().commit()


def strip_fences(t):
    t = t.strip()
    t = re.sub(r"^```[a-zA-Z]*\s*", "", t)
    t = re.sub(r"\s*```$", "", t)
    return t.strip()


@app.route("/teacher/assistant")
@login_required
def assistant():
    chapters = db().execute("SELECT number,title,standard FROM chapters"
                            " ORDER BY number").fetchall()
    return render_template("assistant.html", chapters=chapters,
                           model=API_MODEL, kinds=list(PROMPTS))


@app.route("/api/ai/generate", methods=["POST"])
@login_required
def ai_generate():
    data = request.get_json(silent=True) or {}
    kind = data.get("kind", "")
    topic = (data.get("topic") or "").strip()
    context = (data.get("context") or "").strip()
    count = data.get("count") or 4
    if kind not in PROMPTS:
        return jsonify(ok=False, error="Unknown request type."), 400
    if not topic and not context:
        return jsonify(ok=False, error="Describe the topic you want help with."), 400

    user = "Topic: %s" % topic if topic else ""
    if kind == "questions":
        try:
            count = max(1, min(12, int(count)))
        except Exception:
            count = 4
        user += "\nWrite exactly %d questions, mixing the three types." % count
    if context:
        user += "\n\nExisting material for reference:\n%s" % context[:6000]

    text, err = call_claude(PROMPTS[kind], user.strip(),
                            max_tokens=3000 if kind == "questions" else 2000)
    if err:
        log_ai(kind, topic or context[:80], False, err)
        return jsonify(ok=False, error=err), 502
    log_ai(kind, topic or context[:80], True)

    if kind == "questions":
        try:
            items = json.loads(strip_fences(text))
            assert isinstance(items, list)
        except Exception:
            return jsonify(ok=False, error="The assistant did not return usable JSON. "
                           "Try again, or reword the topic.", raw=text[:1500]), 502
        clean = []
        for it in items:
            if not isinstance(it, dict):
                continue
            t = it.get("type", "mcq")
            if t not in ("mcq", "multi", "fill"):
                continue
            row = dict(type=t, stem=str(it.get("stem", "")).strip(),
                       explanation=str(it.get("explanation", "")).strip(),
                       skill_tag=str(it.get("skill_tag", "")).strip(),
                       difficulty=it.get("difficulty", "medium"))
            if t == "fill":
                acc = [str(x) for x in (it.get("accept") or []) if str(x).strip()]
                if not acc or not row["stem"]:
                    continue
                row.update(options=[], answer=[], accept=acc,
                           display_answer=str(it.get("display_answer") or acc[0]),
                           unit=str(it.get("unit") or ""))
            else:
                opts = [str(x) for x in (it.get("options") or []) if str(x).strip()]
                ans = sorted({int(i) for i in (it.get("answer") or [])
                              if isinstance(i, int) and 0 <= i < len(opts)})
                if len(opts) < 2 or not ans:
                    continue
                if t == "mcq" and len(ans) != 1:
                    t = row["type"] = "multi"
                keys = ["A", "B", "C", "D", "E", "F"]
                row.update(options=opts, answer=ans, accept=[], unit="",
                           display_answer=" and ".join(keys[i] for i in ans))
            clean.append(row)
        if not clean:
            return jsonify(ok=False, error="No valid questions came back. Try again."), 502
        return jsonify(ok=True, kind=kind, questions=clean)

    return jsonify(ok=True, kind=kind, text=text)


@app.route("/api/ai/accept", methods=["POST"])
@login_required
def ai_accept():
    """Save a reviewed AI draft into the database, tagged as an AI draft."""
    data = request.get_json(silent=True) or {}
    number = data.get("chapter")
    row = db().execute("SELECT * FROM chapters WHERE number=?", (number,)).fetchone()
    if not row:
        return jsonify(ok=False, error="Choose a chapter to add this to."), 400
    author = current_user()["display_name"]

    if data.get("questions"):
        n = 0
        for q in data["questions"]:
            pos = db().execute("SELECT COALESCE(MAX(position),0)+1 p FROM questions"
                               " WHERE chapter_id=?", (row["id"],)).fetchone()["p"]
            db().execute(
                "INSERT INTO questions (chapter_id,position,type,stem,options,answer,"
                "accept,display_answer,unit,explanation,skill_tag,difficulty,source,"
                "author,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,'ai',?,?)",
                (row["id"], pos, q.get("type", "mcq"), q.get("stem", ""),
                 json.dumps(q.get("options") or []), json.dumps(q.get("answer") or []),
                 json.dumps(q.get("accept") or []), q.get("display_answer", ""),
                 q.get("unit", ""), q.get("explanation", ""), q.get("skill_tag", ""),
                 q.get("difficulty", "medium"), author, now()))
            n += 1
        db().commit()
        return jsonify(ok=True, added=n,
                       redirect=url_for("questions_list", number=number))

    text = (data.get("text") or "").strip()
    if not text:
        return jsonify(ok=False, error="There is nothing to save."), 400
    body = (row["body_md"] or "").rstrip() + "\n\n" + text + "\n"
    db().execute("UPDATE chapters SET body_md=?, source=?, author=?, updated=?"
                 " WHERE id=?",
                 (body, "ai" if row["source"] == "curriculum" else row["source"],
                  author, now(), row["id"]))
    db().commit()
    return jsonify(ok=True, redirect=url_for("chapter", number=number))


@app.errorhandler(404)
def nf(e):
    return render_template("404.html"), 404


if __name__ == "__main__":
    init_db()
    app.run(host="127.0.0.1", port=int(os.environ.get("PORT", 5000)), debug=False)
